version: '3.8'

services:
  node:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    container_name: node
    env_file: .env
    networks:
      - app-network
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    restart: on-failure
    depends_on:
      - db

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    env_file: .env
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    restart: on-failure

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge